id: P010540
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1GS60386
  title: བོད་སྨན་གཏེར་དངོས་རིག་པ
  author: ''
  volumes:
    c43d341f8d764deb99a324df50b79891:
      image_group_id: I1GS60388
      title: ''
      volume_number: 1
      total_pages: 246
      base_file: v001.txt
