id: I4BE814E4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T10:49:02+00:00'
last_modified: '2022-06-08T14:21:23.762046+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1GS60386
  title: བོད་སྨན་གཏེར་དངོས་རིག་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    57A7:
      image_group_id: I1GS60388
      title: ''
      total_pages: 246
      order: 1
      base_file: 57A7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
